name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    name: Build & test on ${{ matrix.os }} / ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Install cross for ARM64 targets
      - name: Install cross for ARM64 targets
        if: contains(matrix.target, 'aarch64')
        run: cargo install cross --force

      # Add Rust target for all targets
      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]] || [[ "${{ matrix.target }}" == "aarch64-pc-windows-msvc" ]]; then
            cross build --target ${{ matrix.target }} --release
          else
            cargo build --target ${{ matrix.target }} --release
          fi

      - name: Test
        run: |
          if [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]] || [[ "${{ matrix.target }}" == "aarch64-pc-windows-msvc" ]]; then
            cross test --target ${{ matrix.target }} -- --nocapture
          else
            cargo test --target ${{ matrix.target }} -- --nocapture
          fi