name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    # optionally you can limit to certain events:
    # types: [opened, synchronize, reopened]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    name: Build & test on ${{ matrix.os }} / ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up QEMU for ARM64
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: cargo build
        run: cargo build --target ${{ matrix.target }} --release

      - name: cargo test
        run: cargo test --target ${{ matrix.target }} -- --nocapture
